arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - $(arg tf_prefix)shoulder_pan_joint
    - $(arg tf_prefix)shoulder_lift_joint
    - $(arg tf_prefix)elbow_joint
    - $(arg tf_prefix)wrist_1_joint
    - $(arg tf_prefix)wrist_2_joint
    - $(arg tf_prefix)wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    $(arg tf_prefix)shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    $(arg tf_prefix)shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    $(arg tf_prefix)elbow_joint: {trajectory: 0.1, goal: 0.1}
    $(arg tf_prefix)wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    $(arg tf_prefix)wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    $(arg tf_prefix)wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10


# Single joint controllers
shoulder_pan_joint_position_controller: #input: one joint velocity
  type: position_controllers/JointPositionController
  joint: $(arg tf_prefix)shoulder_pan_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
shoulder_lift_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg tf_prefix)shoulder_lift_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
elbow_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg tf_prefix)elbow_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
wrist_1_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg tf_prefix)wrist_1_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
wrist_2_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg tf_prefix)wrist_2_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
wrist_3_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: $(arg tf_prefix)wrist_3_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

# Pass an array of joint velocities directly to the joints
joint_group_vel_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - $(arg tf_prefix)shoulder_pan_joint
    - $(arg tf_prefix)shoulder_lift_joint
    - $(arg tf_prefix)elbow_joint
    - $(arg tf_prefix)wrist_1_joint
    - $(arg tf_prefix)wrist_2_joint
    - $(arg tf_prefix)wrist_3_joint

# TODO: PID need to be calibrated carefully    
  # gains:
  #   $(arg tf_prefix)shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
  #   $(arg tf_prefix)shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
  #   $(arg tf_prefix)elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
  #   $(arg tf_prefix)wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
  #   $(arg tf_prefix)wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
  #   $(arg tf_prefix)wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}

arm_vel_based_pos_traj_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - $(arg tf_prefix)shoulder_pan_joint
    - $(arg tf_prefix)shoulder_lift_joint
    - $(arg tf_prefix)elbow_joint
    - $(arg tf_prefix)wrist_1_joint
    - $(arg tf_prefix)wrist_2_joint
    - $(arg tf_prefix)wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    $(arg tf_prefix)shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    $(arg tf_prefix)shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    $(arg tf_prefix)elbow_joint: {trajectory: 0.1, goal: 0.1}
    $(arg tf_prefix)wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    $(arg tf_prefix)wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    $(arg tf_prefix)wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  125 
  action_monitor_rate: 10
  gains:
    $(arg tf_prefix)shoulder_pan_joint: {p: 50.0,  i: 0.0, d: 0.1, i_clamp: 1}
    $(arg tf_prefix)shoulder_lift_joint: {p: 50.0,  i: 0.0, d: 0.1, i_clamp: 1}
    $(arg tf_prefix)elbow_joint: {p: 50.0,  i: 0.0, d: 0.1, i_clamp: 1}
    $(arg tf_prefix)wrist_1_joint: {p: 50.0,  i: 0.0, d: 0.1, i_clamp: 1}
    $(arg tf_prefix)wrist_2_joint: {p: 50.0,  i: 0.0, d: 0.1, i_clamp: 1}
    $(arg tf_prefix)wrist_3_joint: {p: 50.0,  i: 0.0, d: 0.1, i_clamp: 1}