controller_list:
  - name: arm_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    default: true
    joints:
      - $(arg tf_prefix)shoulder_pan_joint
      - $(arg tf_prefix)shoulder_lift_joint
      - $(arg tf_prefix)elbow_joint
      - $(arg tf_prefix)wrist_1_joint
      - $(arg tf_prefix)wrist_2_joint
      - $(arg tf_prefix)wrist_3_joint

#  - name: arm_velocity_controller
#    action_ns: "follow_joint_trajectory"
#    type: FollowJointTrajectory
#    default: true
#    joints:
#      - $(arg tf_prefix)shoulder_pan_joint
#      - $(arg tf_prefix)shoulder_lift_joint
#      - $(arg tf_prefix)elbow_joint
#      - $(arg tf_prefix)wrist_1_joint
#      - $(arg tf_prefix)wrist_2_joint
#      - $(arg tf_prefix)wrist_3_joint
